### ISSUE TITLE
Readinessprobe panics with latest kiam source

### ISSUE THREAD

**Issue by roffe** [uswitch/kiam#133]
Tried building kiam from source as i wanted the new metrics stuff ( working on a dashboard )

But now kiam server is failing readiness probes

```
 Warning  Unhealthy  12s                kubelet, ip-10-0-118-76.eu-west-1.compute.internal  Readiness probe failed: panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x85fbf2]

goroutine 1 [running]:
github.com/uswitch/kiam/vendor/gopkg.in/alexcesaro/statsd%2ev2.(*Client).skip(0x0, 0x2ac8df26)
  /Users/jbk/go/src/github.com/uswitch/kiam/vendor/gopkg.in/alexcesaro/statsd.v2/statsd.go:87 +0x22
github.com/uswitch/kiam/vendor/gopkg.in/alexcesaro/statsd%2ev2.(*Client).Timing(0x0, 0x13b665e, 0x12, 0x11b1100, 0xc420499bf8)
  /Users/jbk/go/src/github.com/uswitch/kiam/vendor/gopkg.in/alexcesaro/statsd.v2/statsd.go:105 +0x2f
github.com/uswitch/kiam/vendor/gopkg.in/alexcesaro/statsd%2ev2.Timing.Send(0xbed133c3eac04d7a, 0x3b6ebd6, 0x1d01280, 0x0, 0x13b665e, 0x12)
  /Users/jbk/go/src/github.com/uswitch/kiam/vendor/gopkg.in/alexcesaro/statsd.v2/statsd.go:132 +0xaa
github.com/uswitch/kiam/pkg/server.(*KiamGateway).Health(0xc42000a100, 0x150e520, 0xc420134420, 0xc420406060, 0x2, 0x0, 0x0)
  /Users/jbk/go/src/github.com/uswitch/kiam/pkg/server/gateway.go:156 +0x150
main.(*healthCommand).Run.func1(0xc42000a140, 0xc42000a140)
  /Users/jbk/go/src/github.com/uswitch/kiam/cmd/kiam/health.go:55 +0x4e
github.com/uswitch/kiam/vendor/github.com/cenkalti/backoff.RetryNotify(0xc42000a120, 0x14f7420, 0xc42000a140, 0x0, 0xc42000a100, 0x14f7420)
  /Users/jbk/go/src/github.com/uswitch/kiam/vendor/github.com/cenkalti/backoff/retry.go:37 +0x88
github.com/uswitch/kiam/vendor/github.com/cenkalti/backoff.Retry(0xc42000a120, 0x14f7420, 0xc42000a140, 0x14f7420, 0xc42000a140)
  /Users/jbk/go/src/github.com/uswitch/kiam/vendor/github.com/cenkalti/backoff/retry.go:25 +0x48
main.(*healthCommand).Run(0xc4203d6e00)
  /Users/jbk/go/src/github.com/uswitch/kiam/cmd/kiam/health.go:65 +0x29a
main.main()
           /Users/jbk/go/src/github.com/uswitch/kiam/cmd/kiam/main.go:38 +0x212
  Warning  Unhealthy  2s  kubelet, ip-10-0-118-76.eu-west-1.compute.internal  Readiness probe failed: panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x85fbf2]

goroutine 1 [running]:
github.com/uswitch/kiam/vendor/gopkg.in/alexcesaro/statsd%2ev2.(*Client).skip(0x0, 0x2ac731c2)
  /Users/jbk/go/src/github.com/uswitch/kiam/vendor/gopkg.in/alexcesaro/statsd.v2/statsd.go:87 +0x22
github.com/uswitch/kiam/vendor/gopkg.in/alexcesaro/statsd%2ev2.(*Client).Timing(0x0, 0x13b665e, 0x12, 0x11b1100, 0xc42049bbf8)
  /Users/jbk/go/src/github.com/uswitch/kiam/vendor/gopkg.in/alexcesaro/statsd.v2/statsd.go:105 +0x2f
github.com/uswitch/kiam/vendor/gopkg.in/alexcesaro/statsd%2ev2.Timing.Send(0xbed133c66abe14f4, 0x3b4bcdc, 0x1d01280, 0x0, 0x13b665e, 0x12)
  /Users/jbk/go/src/github.com/uswitch/kiam/vendor/gopkg.in/alexcesaro/statsd.v2/statsd.go:132 +0xaa
github.com/uswitch/kiam/pkg/server.(*KiamGateway).Health(0xc420106260, 0x150e520, 0xc420150060, 0xc4202022e0, 0x2, 0x0, 0x0)
  /Users/jbk/go/src/github.com/uswitch/kiam/pkg/server/gateway.go:156 +0x150
main.(*healthCommand).Run.func1(0xc4201062a0, 0xc4201062a0)
  /Users/jbk/go/src/github.com/uswitch/kiam/cmd/kiam/health.go:55 +0x4e
github.com/uswitch/kiam/vendor/github.com/cenkalti/backoff.RetryNotify(0xc420106280, 0x14f7420, 0xc4201062a0, 0x0, 0xc420106200, 0x14f7420)
  /Users/jbk/go/src/github.com/uswitch/kiam/vendor/github.com/cenkalti/backoff/retry.go:37 +0x88
github.com/uswitch/kiam/vendor/github.com/cenkalti/backoff.Retry(0xc420106280, 0x14f7420, 0xc4201062a0, 0x14f7420, 0xc4201062a0)
  /Users/jbk/go/src/github.com/uswitch/kiam/vendor/github.com/cenkalti/backoff/retry.go:25 +0x48
main.(*healthCommand).Run(0xc4203cb5e0)
  /Users/jbk/go/src/github.com/uswitch/kiam/cmd/kiam/health.go:65 +0x29a
main.main()
  /Users/jbk/go/src/github.com/uswitch/kiam/cmd/kiam/main.go:38 +0x212
```

**Comment by roffe** [comment]
My server manifest
```
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  namespace: kube-system
  name: kiam-server
spec:
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9620"
      labels:
        app: kiam
        role: server
    spec:
      serviceAccountName: kiam-server
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
      nodeSelector:
        kubernetes.io/role: master
      volumes:
        - name: ssl-certs
          hostPath:
            path: /etc/ssl/certs
        - name: tls
          secret:
            secretName: kiam-server-tls
      containers:
        - name: kiam
          image: roffe/kiam-git:v2.8-25-g9c824ff
          imagePullPolicy: Always
          command:
            - /kiam
          args:
            - server
            - --json-log
            - --bind=0.0.0.0:443
            - --cert=/etc/kiam/tls/server.pem
            - --key=/etc/kiam/tls/server-key.pem
            - --ca=/etc/kiam/tls/ca.pem
            - --role-base-arn-autodetect
            - --level=warn
            - --sync=1m
            - --prometheus-listen-addr=0.0.0.0:9620
            - --prometheus-sync-interval=5s
          volumeMounts:
            - mountPath: /etc/ssl/certs
              name: ssl-certs
            - mountPath: /etc/kiam/tls
              name: tls
          livenessProbe:
            exec:
              command:
              - /kiam
              - health
              - --cert=/etc/kiam/tls/server.pem
              - --key=/etc/kiam/tls/server-key.pem
              - --ca=/etc/kiam/tls/ca.pem
              - --server-address=localhost:443
              - --server-address-refresh=2s
              - --timeout=5s
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 10
          readinessProbe:
            exec:
              command:
              - /kiam
              - health
              - --cert=/etc/kiam/tls/server.pem
              - --key=/etc/kiam/tls/server-key.pem
              - --ca=/etc/kiam/tls/ca.pem
              - --server-address=localhost:443
              - --server-address-refresh=2s
              - --timeout=5s
            initialDelaySeconds: 3
            periodSeconds: 10
            timeoutSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: kiam-server
  namespace: kube-system
spec:
  clusterIP: None
  selector:
    app: kiam
    role: server
  ports:
  - name: grpclb
    port: 443
    targetPort: 443
    protocol: TCP
```
