### ISSUE TITLE
deploy/server.yaml healthchecks failing

### ISSUE THREAD

**Issue by allandegnan** [uswitch/kiam#17]
Deployed to a 1.8 kops cluster.  Generated Server and Client TLS certs using CFSSL with localhost and kiam-server as server hosts, and put these in as a secret with the ca.pem

Agent starts fine and I can see the health-check in the agents logs (bit annoying, but lets me know it think it's alive) but the server just starts up then shuts down without ever being marked as ready.  

A describe on the pod tells me the shutdown is because of a liveness fail and this is spammed:

```
time="2017-12-21T11:32:24Z" level=warning msg="error checking health: rpc error: code = Unavailable desc = there is no connection available"
```
Removing the healthchecks appear to allow the server to run, and I see some logs about it finding annotations, but I've yet to achieve an assumed role yet, so it's possible I've done something wrong. :)

**Comment by pingles** [comment]
The health-checks OTOH still use the grpc load-balancing stuff to connect (even if it specifies `localhost`), I wonder whether its just that when the health-check process starts its not had enough time to resolve to the pods and exits. Are you using the same timeouts/retry limits? 

I've not checked in the grpc library code but maybe there's a difference to the way it connects if you specify `127.0.0.1` rather than with `localhost`?

**Comment by allandegnan** [comment]
Did not help.

```    
Liveness:       exec [/health --cert=/etc/kiam/tls/server.pem --key=/etc/kiam/tls/server-key.pem --ca=/etc/kiam/tls/ca.pem --server-address=127.0.0.1:443 --server-address-refresh=2s --timeout=5s] delay=10s timeout=10s period=10s #success=1 #failure=3
    Readiness:      exec [/health --cert=/etc/kiam/tls/server.pem --key=/etc/kiam/tls/server-key.pem --ca=/etc/kiam/tls/ca.pem --server-address=127.0.0.1:443 --server-address-refresh=2s --timeout=5s] delay=3s timeout=10s period=10s #success=1 #failure=3
```

&&

```
Events:
  Type     Reason                 Age   From                                                 Message
  ----     ------                 ----  ----                                                 -------
  Normal   SuccessfulMountVolume  19s   kubelet, ip-172-16-57-53.eu-west-2.compute.internal  MountVolume.SetUp succeeded for volume "ssl-certs"
  Normal   SuccessfulMountVolume  19s   kubelet, ip-172-16-57-53.eu-west-2.compute.internal  MountVolume.SetUp succeeded for volume "kiam-token-xcgd9"
  Normal   SuccessfulMountVolume  19s   kubelet, ip-172-16-57-53.eu-west-2.compute.internal  MountVolume.SetUp succeeded for volume "tls"
  Normal   Pulling                19s   kubelet, ip-172-16-57-53.eu-west-2.compute.internal  pulling image "quay.io/secureweb/kiam:latest"
  Normal   Pulled                 18s   kubelet, ip-172-16-57-53.eu-west-2.compute.internal  Successfully pulled image "quay.io/secureweb/kiam:latest"
  Normal   Created                18s   kubelet, ip-172-16-57-53.eu-west-2.compute.internal  Created container
  Normal   Started                18s   kubelet, ip-172-16-57-53.eu-west-2.compute.internal  Started container
  Warning  Unhealthy              1s    kubelet, ip-172-16-57-53.eu-west-2.compute.internal  Readiness probe failed: time="2017-12-21T12:45:15Z" level=warning msg="error checking health: rpc error: code = Unavailable desc = there is no connection available"
time="2017-12-21T12:45:15Z" level=warning msg="error checking health: rpc error: code = Unavailable desc = there is no connection available"
time="2017-12-21T12:45:15Z" level=warning msg="error checking health: rpc error: code = Unavailable desc = there is no connection available"
time="2017-12-21T12:45:15Z" level=warning msg="error checking health: rpc error: code = Unavailable desc = there is no connection available"
time="2017-12-21T12:45:15Z" level=warning msg="error checking health: rpc error: code = Unavailable desc = there is no connection available"
time="2017-12-21T12:45:15Z" level=warning msg="error checking health: rpc error: code = Unavailable desc = there is no connection available"
```

I'm not sure how this is supposed to work.  Am I suposed to be presenting the server side certs to the health check?

**Comment by pingles** [comment]
We use the server certs/keys as in the deployment config. Silly question but you definitely still have the server bound on port 443?

If you change the server and health checks to use `--level=debug` could you see if there's any more detail about what's happening please.

**Comment by allandegnan** [comment]
Sadly I've turned on debug, but there seems to be no logs from the health binary.

```
{"level":"info","msg":"starting server","time":"2017-12-21T13:32:25Z"}
{"level":"info","msg":"will serve on 0.0.0.0:443","time":"2017-12-21T13:32:25Z"}
{"level":"info","msg":"started cache controller","time":"2017-12-21T13:32:25Z"}
{"level":"info","msg":"started namespace cache controller","time":"2017-12-21T13:32:25Z"}
{"level":"info","msg":"starting credential manager process 0","time":"2017-12-21T13:32:25Z"}
{"level":"info","msg":"starting credential manager process 1","time":"2017-12-21T13:32:25Z"}
{"level":"info","msg":"starting credential manager process 2","time":"2017-12-21T13:32:25Z"}
{"level":"info","msg":"starting credential manager process 3","time":"2017-12-21T13:32:25Z"}
{"level":"info","msg":"starting credential manager process 4","time":"2017-12-21T13:32:25Z"}
{"level":"info","msg":"starting credential manager process 5","time":"2017-12-21T13:32:25Z"}
{"level":"info","msg":"starting credential manager process 6","time":"2017-12-21T13:32:25Z"}
{"level":"info","msg":"starting credential manager process 7","time":"2017-12-21T13:32:25Z"}
{"cache.delta.type":"Sync","cache.object":"namespace","level":"debug","msg":"processing delta","namespace":"fake-namespaces","namespace.permitted":"","time":"2017-12-21T13:32:25Z"}
delta","namespace":"kube-system","namespace.permitted":"","time":"2017-12-21T13:32:25Z"}
{"cache.delta.type":"Sync","cache.object":"namespace","level":"debug","msg":"processing delta","namespace":"echo","namespace.permitted":"","time":"2017-12-21T13:32:25Z"}
{"cache.delta.type":"Sync","cache.object":"namespace","level":"debug","msg":"processing delta","namespace":"example-pod","namespace.permitted":"","time":"2017-12-21T13:32:25Z"}
{"level":"info","msg":"stopping server","time":"2017-12-21T13:36:13Z"}
{"level":"info","msg":"stopped","time":"2017-12-21T13:36:13Z"}
```

Apologies, I'm obviously redacting the logs (saves me an argument) but it's all just more of the same.

Actual deploy file looks like this:-

```
---
apiVersion: apps/v1beta2
kind: DaemonSet
metadata:
  namespace: kube-system
  name: kiam-server
spec:
  selector:
    matchLabels:
      app: kiam
      role: server
  template:
    metadata:
      labels:
        app: kiam
        role: server
    spec:
      serviceAccount: kiam
      tolerations:
      - key: "node-role.kubernetes.io/master"
        effect: "NoSchedule"
        operator: "Exists"
      nodeSelector:
        kubernetes.io/role: master
      volumes:
        - name: ssl-certs
          hostPath:
            path: /usr/share/ca-certificates
        - name: tls
          secret:
            secretName: kiam-server-tls
      containers:
        - name: kiam
          image: quay.io/secureweb/kiam:latest
          imagePullPolicy: Always
          command:
            - /server
          args:
            - --json-log
            - --level=debug
            - --bind=0.0.0.0:443
            - --cert=/etc/kiam/tls/server.pem
            - --key=/etc/kiam/tls/server-key.pem
            - --ca=/etc/kiam/tls/ca.pem
            - --role-base-arn=arn:aws:iam::454579647685:role/
            - --sync=1m
          volumeMounts:
            - mountPath: /etc/ssl/certs
              name: ssl-certs
            - mountPath: /etc/kiam/tls
              name: tls
          livenessProbe:
            exec:
              command:
              - /health
              - --level=debug
              - --cert=/etc/kiam/tls/server.pem
              - --key=/etc/kiam/tls/server-key.pem
              - --ca=/etc/kiam/tls/ca.pem
              - --server-address=localhost:443
              - --server-address-refresh=2s
              - --timeout=5s
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 10
          readinessProbe:
            exec:
              command:
              - /health
              - --level=debug
              - --cert=/etc/kiam/tls/server.pem
              - --key=/etc/kiam/tls/server-key.pem
              - --ca=/etc/kiam/tls/ca.pem
              - --server-address=localhost:443
              - --server-address-refresh=2s
              - --timeout=5s
            initialDelaySeconds: 3
            periodSeconds: 10
            timeoutSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: kiam-server
  namespace: kube-system
spec:
  clusterIP: None
  selector:
    app: kiam
    role: server
  ports:
  - name: grpc
    port: 443
    targetPort: 443
    protocol: TCP
```
