### ISSUE TITLE
Namespace restrictions

### ISSUE THREAD

**Issue by pingles** [uswitch/kiam#2]
We run clusters for multiple different teams. We'd like to use an annotation on the Namespace with a regular expression to control which roles can be assumed by pods in that namespace.

For example:

```yaml
kind: Namespace
metadata:
    name: ecommerce
    annotations:
        iam.amazonaws.com/allowed-roles:
            - ^ecommerce.*
```

It means that cluster operators don't need to modify the namespace each time the user wants to add a new role but also gives users control over where their roles can be used.
