### ISSUE TITLE
How to use cert-manager for kiam certificates

### ISSUE THREAD

**Issue by michas2** [uswitch/kiam#223]
I would like to switch from kube2iam to kiam, because it look like kiam also works fine outside of AWS where no metadata service is present.

This seems to be pretty easy:
```
server:
  roleBaseArn: "arn:aws:iam::...
  extraEnv:
    AWS_ACCESS_KEY_ID: AKIA...
    AWS_SECRET_ACCESS_KEY: ...
```
(Is there any good reason why `roleBaseArn` is required?)

Unfortunately installing is more that `helm install stable/kiam` as I first have to generate certificates somehow. (BTW, in the document below you need to write `--from-file=ca=ca.pem` etc. to create the correct filenames for the chart.)

In https://github.com/uswitch/kiam/blob/master/docs/TLS.md you mention that `cert-manager` would be able to create those certificates for me. Could you please give some example, of a suitable Certificate object and which issuer makes sense in this case?
(Most people, including me, only used cert-manager to request server certificates via acme.)

**Comment by michas2** [comment]
Looks like this should be the right way.
```
apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: selfsigning-issuer
spec:
  selfSigned: {}

---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: example-ca
spec:
  secretName: ca-tls
  commonName: "my-ca"
  isCA: true
  issuerRef:
    name: selfsigning-issuer

---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: ca-issuer
spec:
  ca:
    secretName: ca-tls

---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: agent
spec:
  secretName: agent-tls
  commonName: agent
  issuerRef:
    name: ca-issuer

---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: server
spec:
  secretName: server-tls
  issuerRef:
    name: ca-issuer
  dnsNames:
  - localhost
```
Checking the content of the certificate is possible using: `kubectl get secrets agent-tls -o=jsonpath='{.data.tls\.crt}'|base64 -d|cfssl certinfo -cert -|jq .subject`
