### ISSUE TITLE
Divergent annotations for kiam/kube2iam projects, an end user plea

### ISSUE THREAD

**Issue by whereisaaron** [uswitch/kiam#26]
Hi all and thanks for your efforts on `kiam`, I really like the idea of pre-caching credentials for faster container starts.

As an end user it would be fantastic if the `kaim` and `kube2iam` implementations could agree to support that same annotations. This make it easier for `kube2iam` users to switch to `kiam` or to try it and switch back. Or to deploy applications to two clusters, one using each implementation.

Right now the Pod annotation is the same for both - **fantastic!**
```
kind: Pod
metadata:
  name: foo
  namespace: iam-example
  annotations:
    iam.amazonaws.com/role: reportingdb-reader
```

But the namespace annotation has diverged. `kiam` using a single regex to match roles:
```
kind: Namespace
metadata:
  name: iam-example
  annotations:
    iam.amazonaws.com/permitted: ".*"
```
And `kubei2iam` uses a list of roles or role wildcards:
```
Kind: Namespace
metadata:
  name: iam-example
  annotations:
    iam.amazonaws.com/allowed-roles:
    - "role-arn"
    - "my-custom-path/*"
    - "*"
```
Now I am sure both projects had their reasons and preferences. But again, as an end users of both these great projects, I look at the divergent namespace annotations and say "Really!??" 😄 

IMHO, it doesn't seem like either approach is significantly better in any practical way, or in a way that makes this divergence beneficial to users. I feel the use cases for compatibility are strong, and I don't perceive what the use cases are for this divergence?

**Pretty please, could the projects not make friends, get drunk together if necessary, and pick either or both namespace annotation options, and both projects support the same one(s)?** 🍻 

Or second best, if you can't agree, could `kiam` also support `iam.amazonaws.com/allowed-roles` by compiling the list of `allowed-roles` roles into a regex to use internally?
