### ISSUE TITLE
Kiam v3.4.0 / Helm Charts v4.2.0

### ISSUE THREAD

**Issue by ArchiFleKs** [uswitch/kiam#321]
I can't get v3.4 to work with the latest helm charts: here are my values:

```
psp:
  create: true
agent:
  image:
    tag: ${var.kiam["version"]}
  host:
    interface: "eni+"
    iptables: true
  updateStrategy: "RollingUpdate"
  extraHostPathMounts:
    - name: ssl-certs
      mountPath: /etc/ssl/certs
      hostPath: /etc/pki/ca-trust/extracted/pem
      readOnly: true
  tolerations: ${var.kiam["server_use_host_network"] ? "[{'operator': 'Exists'}]" : "[]"}
  whiteListRouteRegexp: "^(/latest/dynamic/instance-identity/document|/latest/meta-data/placement/availability-zone)$"
server:
  service:
    targetPort: 11443
  useHostNetwork: ${var.kiam["server_use_host_network"]}
  image:
    tag: ${var.kiam["version"]}
  assumeRoleArn: ${aws_iam_role.eks-kiam-server-role[0].arn}
  extraHostPathMounts:
    - name: ssl-certs
      mountPath: /etc/ssl/certs
      hostPath: /etc/pki/ca-trust/extracted/pem
      readOnly: true
  extraEnv:
    - name: AWS_DEFAULT_REGION
      value: ${var.aws["region"]}
    - name: AWS_ACCESS_KEY_ID
      value: ${aws_iam_access_key.eks-kiam-user-key[0].id}
    - name: AWS_SECRET_ACCESS_KEY
      value: ${aws_iam_access_key.eks-kiam-user-key[0].secret}
```

This works fine with v3.3

**Comment by ArchiFleKs** [comment]
Sorry here are the computed values:

```
REVISION: 1                                                                                                                                                                                                                              
RELEASED: Tue Nov  5 18:30:42 2019                                                                                                                                                                                                       
CHART: kiam-4.2.0                                                                                                                                                                                                                        
USER-SUPPLIED VALUES:                                                                                                                                                                                                                    
agent:                                                                                                                                                                                                                                   
  extraHostPathMounts:                                                                                                                                                                                                                   
  - hostPath: /etc/pki/ca-trust/extracted/pem                                                                                                                                                                                            
    mountPath: /etc/ssl/certs                                                                                                                                                                                                            
    name: ssl-certs                                                                                                                                                                                                                      
    readOnly: true                                                                                                                                                                                                                       
  host:                                                                                                                                                                                                                                  
    interface: eni+                                                                                                                                                                                                                      
    iptables: true                                                                                                                                                                                                                       
  image:                                                                                                                                                                                                                                 
    tag: v3.4                                                                                                                                                                                                                            
  tolerations:                                                                                                                                                                                                                           
  - operator: Exists                                                                                                                                                                                                                     
  updateStrategy: RollingUpdate                                                                                                                                                                                                          
  whiteListRouteRegexp: ^(/latest/dynamic/instance-identity/document|/latest/meta-data/placement/availability-zone)$                                                                                                                     
psp:                                                                                                                                                                                                                                     
  create: true                
server:                                    
  assumeRoleArn: arn:aws:iam::REDACTED:role/kiam-server-role                                 
  extraEnv:                                      
  - name: AWS_DEFAULT_REGION                       
    value: eu-west-3                         
  - name: AWS_ACCESS_KEY_ID                                                                                         
    value: REDACTED                          
  - name: AWS_SECRET_ACCESS_KEY                                                                                                                                                                                                          
    value: REDACTED                                                                                                                                                                                    
  extraHostPathMounts:                                                                                                                                                                                                                   
  - hostPath: /etc/pki/ca-trust/extracted/pem                                                                                                                                                                                            
    mountPath: /etc/ssl/certs                                                                                                                                                                                                            
    name: ssl-certs                                                                                                                                                                                                                      
    readOnly: true                              
  image:                                                                                                                                                                                                                                 
    tag: v3.4                                                                                                                                                                                                                            
  service:                                                                                                                                                                                                                               
    targetPort: 11443                                                                                                                                                                                                                    
  useHostNetwork: true                      
```
