### ISSUE TITLE
[Feature] Allow setting of default role on namespace level.

### ISSUE THREAD

**Issue by jralph** [uswitch/kiam#379]
It would be very handy to be able to set a default role all pods within a namespace should receive, if no specific role is assigned.

This could be added along side the `permitted` annotation. A good example of this would be for third party ci/cd tools that run on your infrastructure. You could assign a ci/cd role to the namespace they spin runners up in.

```yaml
kind: Namespace
metadata:
  name: cicd-runners
  annotations:
    iam.amazonaws.com/permitted: ".*"
    iam.amazonaws.com/default: "cicd-runner-role"
```
