### ISSUE TITLE
Unable to access ec2 meta data endpoints with kiam deployed on AWS EKS

### ISSUE THREAD

**Issue by nehagokral** [uswitch/kiam#422]
I am trying to access the ec2 metadata endpoints from within my pod, but when I do that I get the following error:
```
:/# curl http://169.254.169.254/latest/meta-data
request blocked by whitelist-route-regexp "^$": /latest/meta-data
```

I am using helm to deploy the kiam configuration. I have added the path to the whiteListRouteRegexp:

```
agent:
  whiteListRouteRegexp: "/latest/meta-data"
  host:
    iptables: true
    interface: eni+
```

 But I am still getting this error. Is there a way to allow requests to these endpoints?
