### ISSUE TITLE
kiam chart 6.1.0 doesn't seem to be published

### ISSUE THREAD

**Issue by joshsleeper** [uswitch/kiam#481]
despite #474 being merged and supposedly providing chart version `6.1.0`, I'm only seeing chart version `6.0.0` present in `index.yaml`.

you can retrieve the latest chart index like so:

```sh
wget https://uswitch.github.io/kiam-helm-charts/charts/index.yaml
```
and you should be able to see that the latest release listed is:

```yaml
apiVersion: v1
entries:
  kiam:
  - apiVersion: v1
    appVersion: "4"
    created: "2021-01-06T11:02:00.432946437Z"
    description: Integrate AWS IAM with Kubernetes
    digest: 4312f648dc5568005e508739f332a81ebfa79d732ce9804f16bbc39cd4f83f98
    engine: gotpl
    home: https://github.com/uswitch/kiam
    icon: https://user-images.githubusercontent.com/44974642/63503185-ee2ce880-c4c6-11e9-9a65-c398db914289.png
    keywords:
    - kiam
    - aws
    - iam
    - security
    maintainers:
    - email: cloud@uswitch.com
      name: uswitch
    name: kiam
    sources:
    - https://github.com/uswitch/kiam
    urls:
    - kiam-6.0.0.tgz
    version: 6.0.0
```
