### ISSUE TITLE
Unknown health check type None in docker logs

### ISSUE THREAD

**Issue by tasdikrahman** [uswitch/kiam#49]
Was going through the docker journald logs on one of the nodes where kiam-server is scheduled, saw something like 

```
Mar 29 07:15:09 ip-10-1-71-111 env[841]: time="2018-03-29T07:15:09.037099505Z" level=warning msg="Unknown healthcheck type 'NONE' (expected 'CMD') in container 24ff319a210f5cf9a1908105647d7c1873bd42a91a4a8c77184dbf8c59031d8d"
Mar 29 07:18:29 ip-10-1-71-111 env[841]: time="2018-03-29T07:18:29.922256047Z" level=warning msg="Unknown healthcheck type 'NONE' (expected 'CMD') in container 4c1ebaf2ca9c0c9d2f2a4cdb89795c02a2acf7a61297d333f3fe573385e847f8"
```

The kiam server which went into `CrashLoopBackOff` had logs 

```
{"level":"info","msg":"starting server","time":"2018-03-29T07:18:29Z"}
{"level":"info","msg":"will serve on 0.0.0.0:443","time":"2018-03-29T07:18:29Z"}
{"level":"info","msg":"started cache controller","time":"2018-03-29T07:18:29Z"}
{"level":"info","msg":"started namespace cache controller","time":"2018-03-29T07:18:29Z"}
{"level":"info","msg":"starting credential manager process 0","time":"2018-03-29T07:18:29Z"}
{"level":"info","msg":"starting credential manager process 1","time":"2018-03-29T07:18:29Z"}
{"level":"info","msg":"starting credential manager process 2","time":"2018-03-29T07:18:29Z"}
{"level":"info","msg":"starting credential manager process 3","time":"2018-03-29T07:18:29Z"}
{"level":"info","msg":"starting credential manager process 4","time":"2018-03-29T07:18:29Z"}
{"level":"info","msg":"starting credential manager process 5","time":"2018-03-29T07:18:29Z"}
{"level":"info","msg":"starting credential manager process 6","time":"2018-03-29T07:18:29Z"}
{"level":"info","msg":"starting credential manager process 7","time":"2018-03-29T07:18:29Z"}
```

server manifest pertaining to liveness and readinessProbe

```
          livenessProbe:
            exec:
              command:
              - /health
              - --cert=/etc/kiam/tls/kiam-server.crt
              - --key=/etc/kiam/tls/kiam-server.key
              - --ca=/etc/kiam/tls/kiam-ca.crt
              - --server-address=localhost:443
              - --server-address-refresh=2s
              - --timeout=5s
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 10
          readinessProbe:
            exec:
              command:
              - /health
              - --cert=/etc/kiam/tls/kiam-server.crt
              - --key=/etc/kiam/tls/kiam-server.key
              - --ca=/etc/kiam/tls/kiam-ca.crt
              - --server-address=localhost:443
              - --server-address-refresh=2s
              - --timeout=5s
            initialDelaySeconds: 3
            periodSeconds: 10
            timeoutSeconds: 10
```
