### ISSUE TITLE
Multiple roles

### ISSUE THREAD

**Issue by paalkr** [uswitch/kiam#89]
Hi

How can I attach multiple roles to a POD using Kiam?

```
    metadata:
      annotations:
        iam.amazonaws.com/role:
        - role1
        - role2
```
obviously does not work

```
    metadata:
      annotations:
        iam.amazonaws.com/role: role1
        iam.amazonaws.com/role: role2
```
will only assign role2, as expected
