### ISSUE TITLE
Kiam server readiness/liveness probe issues (v2.8)

### ISSUE THREAD

**Issue by mattreyuk** [uswitch/kiam#94]
I have Kiam setup on a 3 master cluster - the server runs on two of the three masters with some readiness probes failing but the 3rd node is in a crash loop backoff with the liveness probe failing. The error message is the same for both:
```
probe failed: time="2018-06-18T22:10:41Z" level=fatal msg="error creating server gateway: error waiting for address being available in the balancer: context deadline exceeded"
```
 Looking in the server logs for the failing pod, I just see it startup, lots of `found role`, `requesting credentials` and then finally `stopped`.
I'm using Image: `quay.io/uswitch/kiam:v2.8` and the standard probe definitions from `/deploy/server.yaml` (this is a `kops` 1.9 cluster so I changed the cert path to `/etc/ssl/certs` and added master tolerations to get it to work).

**Comment by pingles** [comment]
@mattreyuk To get more information could you add the following environment variables to the health check command please:

```GRPC_GO_LOG_SEVERITY_LEVEL=info GRPC_GO_LOG_VERBOSITY_LEVEL=8```

https://github.com/uswitch/kiam/issues/17 had a similar problem- a connection error inside the gRPC client but the log data/errors were being masked.

**Comment by maauso** [comment]
Hi guys, 
I found the same problem, I'm using EKS and I created a different workers stacks, in order to have Kiam servers running on it, then I will be able to apply Server IAM Role. 

The Kiam version that I'm using is 2.8, moreover in order to have a dedicate nodes for kaim pods I'm using the following yaml file 

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: kube-system
  name: kiam-server
spec:
  replicas: 3
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9620"
      labels:
        app: kiam
        role: server
    spec:
      serviceAccountName: kiam-server
      affinity:
        podAntiAffinity:                                 
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: kubernetes.io/hostname   
      nodeSelector:
        beta.kubernetes.io/instance-type: t2.medium
      volumes:
        - name: ssl-certs
          hostPath:
            # for AWS linux or RHEL distros
            path: /etc/pki/ca-trust/extracted/pem/
            #path: /usr/share/ca-certificates
        - name: tls
          secret:
            secretName: kiam-server-tls
      containers:
        - name: kiam
          image: quay.io/uswitch/kiam:v2.8
          imagePullPolicy: Always
          env:
          - name: GRPC_GO_LOG_SEVERITY_LEVEL
            value: "info"
          - name: GRPC_GO_LOG_VERBOSITY_LEVEL
            value: "8"
          command:
            - /server
          args:
            - --json-log
            - --bind=0.0.0.0:443
            - --cert=/etc/kiam/tls/server.pem
            - --key=/etc/kiam/tls/server-key.pem
            - --ca=/etc/kiam/tls/ca.pem
            - --role-base-arn-autodetect
            - --sync=1m
            - --prometheus-listen-addr=0.0.0.0:9620
            - --prometheus-sync-interval=5s
          volumeMounts:
            - mountPath: /etc/ssl/certs
              name: ssl-certs
            - mountPath: /etc/kiam/tls
              name: tls
          livenessProbe:
            exec:
              command:
              - /health
              - --cert=/etc/kiam/tls/server.pem
              - --key=/etc/kiam/tls/server-key.pem
              - --ca=/etc/kiam/tls/ca.pem
              - --server-address=localhost:443
              - --server-address-refresh=2s
              - --timeout=5s
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 10
          readinessProbe:
            exec:
              command:
              - /health
              - --cert=/etc/kiam/tls/server.pem
              - --key=/etc/kiam/tls/server-key.pem
              - --ca=/etc/kiam/tls/ca.pem
              - --server-address=localhost:443
              - --server-address-refresh=2s
              - --timeout=5s
            initialDelaySeconds: 3
            periodSeconds: 10
            timeoutSeconds: 10
```
But, I have the same error
```
Readiness probe failed: INFO: 2018/06/19 12:39:09 ccBalancerWrapper: updating state and picker called by balancer: IDLE, 0xc4203d1380 INFO: 2018/06/19 12:39:09 dialing to target with scheme: "" INFO: 2018/06/19 12:39:09 could not get resolver for scheme: "" INFO: 2018/06/19 12:39:09 balancerWrapper: is pickfirst: false time="2018-06-19T12:39:09Z" level=fatal msg="error creating server gateway: error waiting for address being available in the balancer: context deadline exceeded"
```
